version: "3"
services:
  weather_spain_backend:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
